# Generated by Django 4.2.6 on 2023-11-22 16:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MediaModel",
            fields=[
                (
                    "filename",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("file", models.FileField(upload_to="paperapi/static/media")),
                (
                    "modifiedTime",
                    models.DateTimeField(
                        default=datetime.datetime(2023, 11, 22, 16, 46, 44, 832097)
                    ),
                ),
            ],
            options={
                "db_table": "media",
            },
        ),
        migrations.CreateModel(
            name="PaperModel",
            fields=[
                (
                    "filename",
                    models.CharField(max_length=250, primary_key=True, serialize=False),
                ),
                ("file", models.FileField(upload_to="md/")),
                (
                    "modifiedTime",
                    models.DateTimeField(
                        default=datetime.datetime(2023, 11, 22, 16, 46, 44, 831872)
                    ),
                ),
            ],
            options={
                "db_table": "paper",
            },
        ),
    ]
