# Generated by Django 4.2.6 on 2023-11-23 07:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("paperapi", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mediamodel",
            name="modifiedTime",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="papermodel",
            name="modifiedTime",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
