# Generated by Django 4.2.6 on 2023-11-24 11:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("paperapi", "0002_alter_mediamodel_modifiedtime_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mediamodel",
            name="modifiedTime",
        ),
        migrations.RemoveField(
            model_name="papermodel",
            name="modifiedTime",
        ),
        migrations.AddField(
            model_name="mediamodel",
            name="sha256",
            field=models.CharField(default=None, max_length=65),
        ),
        migrations.AddField(
            model_name="papermodel",
            name="sha256",
            field=models.CharField(default=None, max_length=65),
        ),
    ]
