# Generated by Django 4.2.6 on 2023-11-24 11:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("paperapi", "0003_remove_mediamodel_modifiedtime_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="mediamodel",
            old_name="sha256",
            new_name="hash",
        ),
        migrations.RenameField(
            model_name="papermodel",
            old_name="sha256",
            new_name="hash",
        ),
    ]
