# Generated by Django 4.2.6 on 2023-11-24 11:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("paperapi", "0004_rename_sha256_mediamodel_hash_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mediamodel",
            name="hash",
            field=models.CharField(default=None, max_length=65, null=True),
        ),
        migrations.AlterField(
            model_name="papermodel",
            name="hash",
            field=models.CharField(default=None, max_length=65, null=True),
        ),
    ]
