# Generated by Django 4.2.6 on 2023-12-23 05:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("paperapi", "0005_alter_mediamodel_hash_alter_papermodel_hash"),
    ]

    operations = [
        migrations.CreateModel(
            name="NoteData",
            fields=[
                (
                    "filename",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("title", models.CharField(max_length=100)),
                ("pageImage", models.CharField(max_length=200, null=True)),
                ("tags", models.CharField(max_length=70, null=True)),
            ],
            options={
                "db_table": "NoteData",
            },
        ),
    ]
